#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
general:
  experiment_name: "yelp_afm_test"
  device: "cuda"
  backend: "polars"
  time_report: False

dashboard:
  wandb:
    enabled: True
    team: "i-buonfrate-politecnico-di-bari"
    project: "EvaluateCars"
    api_key: "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"
    group: "yelp_experiments"
    log_config: True
    upload_checkpoints: False
  codecarbon:
    enabled: True
    save_to_file: True
    output_dir: "results/carbon/"
    tracking_mode: "machine"

writer:
  dataset_name: "Yelp"
  writing_method: "local"
  local_experiment_path: "results/" 
  setup_experiment: True
  save_split: True
  recommendation:
    k: 10 
    save: True

reader:
  loading_strategy: "dataset"
  data_type: "transaction"
  reading_method: "local"
  rating_type: "explicit"
  local_path: "warp_output/yelp_context_ready.tsv"
  sep: "\t"
  header: True
  labels:
    user_id_label: "user_id"
    item_id_label: "item_id"
    rating_label: "rating"
    timestamp_label: "timestamp" 
  context_features: [hour_of_day, day_of_week, is_weekend, season,
                     user_elite, user_experience, city, category,
                     price_range, alcohol, outdoor_seating]
  dtypes: 
    user_id_type: "str"
    item_id_type: "str"
    rating_type: "float32"
    timestamp_type: "str" 

#splitter: 
 # test_splitting:
    #strategy: [temporal_holdout, temporal_leave_k_out, random_holdout, random_leave_k_out, timestamp_slicing]
  #  strategy: "random_holdout" 
  #  ratio: 0.2
    
splitter:
  test_splitting:
    strategy: "temporal_leave_k_out"
    k: 1
  validation_splitting:
    strategy: "temporal_leave_k_out"
    k: 1

models:
  Pop:
    meta:
        save_recs: True

evaluation:
  top_k: [5, 10]
  metrics: ["AUC", "NDCG", "MAP", "MRR", "PRECISION", "RECALL"]
  complex_metrics:
    - name: "ACC"
      params: {}
    - name: "CS"
      params: {}
    - name: "WCS"
      params: {}
    - name: "WCA"
      params: {}
    - name: "Friction"
      params: {}
    - name: "CR"
      params: {}
    - name: "CRC"
      params: {}
    - name: "CGB"
      params: {}
    - name: "CW-nDCG"
      params: {}
    - name: "CW-MAP"
      params: {}
  relevance_threshold: 4.0
  save_per_user: True